---
env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
plugins:
  - prettier
parserOptions:
  sourceType: module
  ecmaVersion: 8
rules:
  prettier/prettier: error
  "no-unused-vars": warn
